my_site/first_app/urls.py
from django.urls import path
from . import views

#register the app name
# URL NAMES
app_name = 'my_app'

# domain.com/first_app/simple_view
urlpatterns = [
    path('', views.example_view, name='example'), # domain.com/first_app
    path('variable/',views.variable_view, name='variable')
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
]


handler404 = 'my_site.views.my_custom_page_not_found_view'

my_site/first_app/models.py
from django.db import models

# Create your models here.

my_site/first_app/views.py
from django.shortcuts import render


# Create your views in here 

def example_view(request):
    # first_app/templates/first_app/example.html
    return render(request,'first_app/example1.html')

def variable_view(request):
    """
    my_var = {
        'first_name': 'rosaLind',
        'last_name' : 'franklin',
        'some_list' : [1,2,3],
        'some_dict' : {
            'inside_key':'inside_value'
        },
        'user_logged_in':True
    }
    """
    return render(request, 'first_app/variable.html')

my_site/my_site/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

def home_view(request):
    return HttpResponse('HOME VIEW!')

def my_custom_page_not_found_view(request, exception):
    return render(request, 'error_view.html',status=404)

my_site/first_app/templates/first_app/example.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>EXAMPLE HTML TEMPLATE CONNECTED!</h1>
    <h1><a href="{% url 'my_app:variable'%}"> CLICK ME TO GO TO VARIABLE </h1>
</body>
</html>

my_site/first_app/templates/first_app/example1.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<h1>THIS IS THE INSIDE THE BLOCK IN EXAMPLE1.HTML</h1>
<img src="{% static 'first_app/django.jpg' %}" style="width:20% ;">
{% endblock %}

my_site/first_app/templates/first_app/variable.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>VARIABLE.HTML</h1>
    <h2>Her name was {{first_name | lower | capfirst}} and her last name was {{last_name | capfirst}}</h2>
    <h2>{{some_list.0}}</h2>
    <h2>{{some_dict.inside_key}}</h2>
    <h2>{# this is a comment #}</h2>
    <br>
    <!--h1>Tags and For loops</h1-->
    <ul>
    {% for k,v in some_dict.items %}
        <li>{{k}} : {{v}}</li>
    {% endfor %}
    </ul>
    <h1>{{some_list}}</h1>
    <br>
    <!-- tags and if else statement-->
    {% if user_logged_in %}
    <h1>Welcome back you logged in</h1>
    {% endif %}
    <!-- tags if else and for-->
    <br>
    <ul>
        {% for num in some_list %}
            {% if num == 2 %}
                <li>TWO</li>
            {% else %}
                <li>{{num}}</li>
            {% endif %}
        {% endfor %}
    </ul>
    <br>
    


</body>
</html>

my_site/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>THIS IS ABOVE THE BLOCK IN BASE.HTML</h1>
    {% block content %}

    {% endblock %}
    <h1>THIS IS BELOW THE BLOCK IN BASE.HTML</h1>
</body>
</html>

my_site/templates/error_view.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>MY CUSTOM 404 PAGE</h1>
</body>
</html>

my_site/templates/first_app/example.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>EXAMPLE HTML CONNECTED!</h1>
</body>
</html>